### ISSUE TITLE
How to use a small picture of a screenshot of the region to match the enlarged picture of the region

### ISSUE THREAD

**Issue by CodeToSurvive1** [strarsis/node-opencv-templatematching-test#2]
hello，
    here，i have a question like the title.
    If i take a screenshot of the region in a small picture,and use the matchTemplate to recognize in the small picture,it will be ok.But if i use the screenshot to match in  enlarged  picture,what i should do ?And the matchTemplate support this ?

**Comment by strarsis** [comment]
What I do (and recommend) would be to reduce the larger image of the two to 
at least the dimensions of the smaller one (or even smaller). 
node-opencv (and underlying opencv) also offers a resize(..., ...) method for this.

**Comment by CodeToSurvive1** [comment]
ok,thank you very much. I will have a try.
